### ISSUE TITLE
How to get the input value ?

### ISSUE THREAD

**Issue by praba2210** [gayathri-perumal/react-native-chip-input#2]

**Comment by Ambalika252252** [comment]
Did you find any solution on this?
I think values are not emitted to the parent.

**Comment by praba2210** [comment]
No, I created my own chip input component after that!

**Comment by gayathrithedev** [comment]
Closing it because duplicate issue.
Check the solution below
[how to get input values?](https://github.com/gayathrithedev/react-native-chip-input/issues/1)
